[tool.poetry]
name = "popular-movies"
version = "1.0.0"
description = "Scrapes a list of popular movies from Rotten Tomatoes."
authors = ["Jonas Stendahl <jonas@stendahl.me>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
beautifulsoup4 = "^4.9.3"
IMDbPY = "^2021.4.18"
requests = "^2.26.0"
sentry-sdk = "^1.5.8"
tmdbv3api = "^1.7.6"

[tool.poetry.group.dev.dependencies]
black = "^21.12-beta.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
